### ISSUE TITLE
morphologica is incompatible with OpenCV 4+

### ISSUE THREAD

**Issue by sebjameswml** [ABRG-Models/morphologica#7]
As reported by @tindzk there are some OpenCV function calls made in morphologica which have been deprecated in OpenCV 4+. Fix this.

**Comment by sebjameswml** [comment]
Fixed with commit 59204c2

**Comment by tindzk** [comment]
Thanks. This fixes the compilation under Arch Linux, but linking still fails. I will open a separate issue.

**Comment by sebjameswml** [comment]
Ok, so this one seems to be ok now.
